# Generated by Django 4.2.4 on 2025-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='active',
            field=models.TextField(default='valeurs par defaut'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.TextField(default=5),
        ),
    ]
