# Generated by Django 4.2.4 on 2025-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_active_alter_produit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='live',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
