# Generated by Django 4.2.4 on 2025-04-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_produit_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
    ]
