# Generated by Django 4.2.4 on 2025-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_produit_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
